server:
  port: 8084

spring:
  application:
    name: legacy-vault
    properties:
      logging.level.org.springframework.security=DEBUG
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:legacyvault}
    username: ${DB_USERNAME:legacy_vault_user}
    password: ${DB_PASSWORD:legacyvault_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS:900}
    refresh-token-ttl-seconds: ${JWT_REFRESH_TOKEN_TTL_SECONDS:604800}
