package com.ltld.app.legacyvault.enums;

public enum AuditAction {
    REGISTER, OTP_SENT, OTP_FAILED, EMAIL_VERIFIED,
    LOGIN, LOGIN_FAILED, ACCOUNT_LOCKED, LOGOUT,
    TOKEN_REFRESH, TOKEN_REFRESH_FAILED,
    VAULT_CREATED, VAULT_DELETED, VAULT_DELETE_DENIED, VAULT_UNLOCK, DOCUMENT_UPLOADED,
    CLAIM_INITIATED, EXECUTOR_REVOKE, RBAC_CHANGE, TOKEN_REUSE_DETECTED, OTP_RATE_LIMITED,
    PASSWORD_RESET_REQUEST, PASSWORD_RESET_SUCCESS, PASSWORD_RESET_FAILED,
    IDENTITY_OTP_SENT, IDENTITY_VERIFIED, IDENTITY_VERIFY_FAILED, IDENTITY_LOCKED, ASSET_VIEWED
}